worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    gzip          on;
    gzip_types    text/plain text/css application/javascript application/json;

    limit_req_zone $binary_remote_addr zone=admin_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=public_limit:10m rate=100r/s;
    limit_req_status 429;

    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location /api/v1/admin/ {
            limit_req zone=admin_limit burst=20 nodelay;
            proxy_pass http://monolith:3000/api/v1/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/public/tournaments {
            limit_req zone=public_limit burst=50 nodelay;
            proxy_pass http://monolith:3000/api/v1/public/tournaments;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/public/top-scorers {
            proxy_pass http://monolith:3000/api/v1/public/top-scorers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/public/ {
            limit_req zone=public_limit burst=200 nodelay;
            proxy_pass http://public-service:3002/api/v1/public/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 86400s;
            chunked_transfer_encoding on;
        }

        location /api/v1/standings/ {
            limit_req zone=public_limit burst=200 nodelay;
            proxy_pass http://standings-service:3001/api/v1/standings/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/monolith/ {
            proxy_pass http://monolith:3000/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/standings/ {
            proxy_pass http://standings-service:3001/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/public/ {
            proxy_pass http://public-service:3002/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/notification/ {
            set $notif http://notification-service:3003;
            proxy_pass $notif/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
