import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useTournament } from '../../context/TournamentContext';
import api from '../../api';

const AUTO_PREFIX = 'Match completed.';

const TYPE_EMOJIS = {
  goal:         '⚽',
  yellow_card:  '🟨',
  red_card:     '🟥',
  substitution: '🔄',
  info:         'ℹ️',
  comment:      '💬',
};

export default function ReportPage() {
  const { matchId }   = useParams();
  const { token }     = useAuth();
  const { selectedTournament } = useTournament();

  const [report, setReport]         = useState(null);
  const [goals, setGoals]           = useState([]);
  const [commentary, setCommentary] = useState([]);
  const [error, setError]           = useState('');

  useEffect(() => {
    api.get(`/api/v1/public/reports/${matchId}`)
      .then(r => setReport(r.data))
      .catch(() => setError('Report not found for this match.'));

    api.get(`/api/v1/admin/matches/${matchId}/goals`)
      .then(r => setGoals(r.data))
      .catch(() => {});

    api.get(`/api/v1/public/matches/${matchId}/commentary`)
      .then(r => setCommentary(r.data))
      .catch(() => {});
  }, [matchId, token]);

  const isAutoGenerated = report?.summary?.startsWith(AUTO_PREFIX);

  return (
    <div className="page">
      <h1>Match Report{selectedTournament ? ` — ${selectedTournament.name}` : ''}</h1>
      {error && <p className="error">{error}</p>}
      {report && (
        <div className="report-card">
          {isAutoGenerated && (
            <span style={{
              display: 'inline-block',
              background: '#e8f5e9',
              color: '#27ae60',
              fontSize: 11,
              fontWeight: 700,
              padding: '2px 10px',
              borderRadius: 12,
              marginBottom: 14,
              letterSpacing: '0.06em',
            }}>
              AUTO-GENERATED
            </span>
          )}
          <p style={{ fontSize: 17, fontWeight: 600, lineHeight: 1.5, marginBottom: 12 }}>
            {report.summary}
          </p>
          <small>Created: {new Date(report.created_at).toLocaleString()}</small>
        </div>
      )}
      {goals.length > 0 && (
        <section>
          <h2>Goal Scorers</h2>
          <table>
            <thead>
              <tr><th>Player</th><th>Team</th><th>Minute</th></tr>
            </thead>
            <tbody>
              {goals.map(g => (
                <tr key={g.id}>
                  <td>{g.player_name}</td>
                  <td>{g.team_name}</td>
                  <td>{g.minute ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}
      {commentary.length > 0 && (
        <section style={{ marginTop: 32 }}>
          <h2>Match Timeline</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {commentary.map(c => (
              <div key={c.id} style={{ display: 'flex', gap: 12, alignItems: 'flex-start', fontSize: 14 }}>
                <span style={{ minWidth: 36, color: '#888', fontVariantNumeric: 'tabular-nums', textAlign: 'right' }}>
                  {c.minute != null ? `${c.minute}'` : '—'}
                </span>
                <span style={{ fontSize: 18, lineHeight: 1 }}>{TYPE_EMOJIS[c.type] || '💬'}</span>
                <span style={{ lineHeight: 1.4 }}>{c.text}</span>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
